- name: Copy backend files
  copy:
    src: /home/circleci/project/backend/dist
    dest: /home/ubuntu/backend

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start